# Generated by Django 3.1.2 on 2020-12-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupletchatbot', '0002_auto_20201202_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='first_couplet',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='second_couplet',
            field=models.CharField(max_length=256),
        ),
    ]
